name: Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PROJECT_NAME: jmpg-developer.github.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.14
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm run test:ci --if-present

      - name: Build (production)
        run: |
          npm run build -- --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**/*